// Copyright 2026 R3D HILLS. All Rights Reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

package core

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/nematollahshojaei/project2markdown/internal/utils"
)

// MaxLineBuffer defines a strict 20MB limit per single raw line to capture ultra-large compressed assets.
const MaxLineBuffer = 1024 * 1024 * 20

// StringWriter interface allows streaming to both physical files and memory buffers concurrently.
type StringWriter interface {
	WriteString(s string) (n int, err error)
}

// GenerateProject encapsulates the core generation logic.
// Security Pillar: Supports dynamic absolute paths while maintaining strict file boundaries.
// Architecture Pillar: Decoupled from UI/CLI using the onProgress callback.
func GenerateProject(
	targetDir, outputFileName, customIgnores, format, includePatterns string,
	removeComments, removeEmptyLines, aiInstructions bool,
	customPrompt string,
	onProgress func(filesProcessed, currentTokens int, currentPath string),
) (string, int, error) {
	var err error
	if targetDir == "" {
		targetDir, err = os.Getwd()
		if err != nil {
			return "", 0, fmt.Errorf("unable to retrieve current working directory: %v", err)
		}
	} else {
		targetDir, err = filepath.Abs(targetDir)
		if err != nil {
			return "", 0, fmt.Errorf("invalid target directory: %v", err)
		}
	}

	if format == "" {
		format = "md"
	}
	projectName := filepath.Base(targetDir)

	if outputFileName == "" {
		outputFileName = projectName + "_context." + format
	} else {
		// Zero-Bug Safety: Ensure the file extension strictly matches the selected format
		expectedExt := "." + format
		if !strings.HasSuffix(strings.ToLower(outputFileName), expectedExt) {
			ext := filepath.Ext(outputFileName)
			if ext != "" {
				outputFileName = strings.TrimSuffix(outputFileName, ext)
			}
			outputFileName += expectedExt
		}
	}

	if !filepath.IsAbs(outputFileName) {
		outputFileName = filepath.Join(targetDir, outputFileName)
	}

	f, err := os.Create(outputFileName)
	if err != nil {
		return "", 0, fmt.Errorf("unable to create output file: %v", err)
	}
	defer f.Close()

	ignoreEngine := NewIgnoreEngine(targetDir)
	ignoreEngine.AddCustomPatterns(customIgnores)

	var treeBuf bytes.Buffer
	generateTree(targetDir, targetDir, "", filepath.Base(outputFileName), &treeBuf, ignoreEngine)
	treeStr := treeBuf.String()

	totalChars := len(treeStr)
	totalTokens := utils.EstimateTokens(treeStr)

	// Build AI Prompts
	promptText := ""
	if customPrompt != "" {
		promptText += customPrompt + "\n\n"
	}
	if aiInstructions {
		promptText += "> **System Instructions for AI:**\n"
		promptText += "> This context was generated by Project2Markdown. When modifying or creating files, output the exact full file content wrapped in standard Markdown code blocks with the file path as a header (e.g., `### File: ProjectName/path/to/file.ext` or XML `<file>` tags). Do not truncate code or add line numbers.\n\n"
	}
	totalTokens += utils.EstimateTokens(promptText)

	// Write Header based on format
	switch format {
	case "json":
		f.WriteString("{\n")
		if promptText != "" {
			f.WriteString("  \"prompt\": \"" + utils.EscapeJSONString(promptText) + "\",\n")
		}
		f.WriteString("  \"project\": \"" + utils.EscapeJSONString(projectName) + "\",\n")
		f.WriteString("  \"tree\": \"" + utils.EscapeJSONString(treeStr) + "\",\n")
		f.WriteString("  \"files\": [\n")
	case "xml":
		f.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
		if promptText != "" {
			f.WriteString("<!--\n" + promptText + "-->\n")
		}
		f.WriteString("<project name=\"" + projectName + "\">\n")
		f.WriteString("  <tree><![CDATA[\n" + treeStr + "  ]]></tree>\n")
	default:
		if promptText != "" {
			f.WriteString(promptText)
		}
		f.WriteString(fmt.Sprintf("# Project Context: %s\n\n", projectName))
		f.WriteString("## Directory Structure\n```text\n")
		f.WriteString(projectName + "/\n" + treeStr + "```\n\n")
	}

	// ==========================================
	// CONCURRENCY ENGINE (Worker Pool)
	// ==========================================
	type fileJob struct {
		path    string
		relPath string
		ext     string
	}

	type fileResult struct {
		relPath         string
		langMarkdownTag string
		content         string
		chars           int
		tokens          int
		err             error
	}

	jobs := make(chan fileJob, 1000)
	results := make(chan fileResult, 1000)
	var wg sync.WaitGroup

	// 1. Start Workers (Based on CPU Cores)
	numWorkers := runtime.NumCPU()
	for i := 0; i < numWorkers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobs {
				// I/O Bound check moved to worker for maximum concurrent speed
				if !utils.IsTextFile(job.path) {
					continue
				}

				langMarkdownTag := strings.TrimPrefix(job.ext, ".")
				if langMarkdownTag == "" {
					langMarkdownTag = "text"
				}

				var buf bytes.Buffer
				chars, tokens, err := streamFileContents(job.path, &buf, format, removeComments, removeEmptyLines, job.ext)

				results <- fileResult{
					relPath:         job.relPath,
					langMarkdownTag: langMarkdownTag,
					content:         buf.String(),
					chars:           chars,
					tokens:          tokens,
					err:             err,
				}
			}
		}()
	}

	// 2. Start Thread-Safe Writer Goroutine
	writerDone := make(chan struct{})
	go func() {
		isFirstFile := true
		filesProcessed := 0
		for res := range results {
			filesProcessed++

			// Trigger progress callback if provided
			if onProgress != nil {
				onProgress(filesProcessed, totalTokens+res.tokens, res.relPath)
			}

			switch format {
			case "json":
				if !isFirstFile {
					f.WriteString(",\n")
				}
				f.WriteString(fmt.Sprintf("    {\n      \"path\": \"%s\",\n      \"content\": \"", utils.EscapeJSONString(res.relPath)))
			case "xml":
				f.WriteString(fmt.Sprintf("  <file path=\"%s\">\n<![CDATA[\n", res.relPath))
			default:
				f.WriteString(fmt.Sprintf("### File: %s/%s\n```%s\n", projectName, res.relPath, res.langMarkdownTag))
			}

			f.WriteString(res.content)
			totalChars += res.chars
			totalTokens += res.tokens

			if res.err != nil && format == "md" {
				f.WriteString(fmt.Sprintf("\n// Error streaming file content: %v\n", res.err))
			}

			switch format {
			case "json":
				f.WriteString("\"\n    }")
			case "xml":
				f.WriteString("\n]]>\n  </file>\n")
			default:
				f.WriteString("\n```\n\n")
			}
			isFirstFile = false
		}

		// Write Project Footer
		switch format {
		case "json":
			f.WriteString("\n  ]\n}\n")
		case "xml":
			f.WriteString("</project>\n")
		}

		close(writerDone)
	}()

	// 3. Walk Directory and Feed Jobs
	err = filepath.WalkDir(targetDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		relPath, relErr := filepath.Rel(targetDir, path)
		if relErr != nil {
			return nil
		}

		if ignoreEngine.IsIgnored(relPath, d.IsDir()) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		info, err := d.Info()
		if err != nil {
			return nil
		}
		if info.Mode()&os.ModeSymlink != 0 || (info.Mode()&os.ModeDevice != 0) {
			return nil
		}

		lowerName := strings.ToLower(d.Name())
		outBase := strings.ToLower(filepath.Base(outputFileName))
		if lowerName == outBase || lowerName == "p2m.exe" || lowerName == "p2m" ||
			lowerName == "project2markdown.exe" || lowerName == "project2markdown.go" ||
			strings.Contains(lowerName, "_context.") {
			return nil
		}

		if !d.IsDir() {
			relPath = filepath.ToSlash(relPath)

			// Include Patterns Logic
			if includePatterns != "" {
				isMatch := false
				incRules := strings.Split(includePatterns, ",")
				for _, rule := range incRules {
					rule = strings.TrimSpace(rule)
					if rule != "" && (strings.Contains(relPath, rule) || strings.HasSuffix(relPath, rule)) {
						isMatch = true
						break
					}
				}
				if !isMatch {
					return nil
				}
			}

			ext := strings.ToLower(filepath.Ext(d.Name()))
			jobs <- fileJob{path: path, relPath: relPath, ext: ext}
		}
		return nil
	})

	// 4. Graceful Shutdown of Concurrency Engine
	close(jobs)
	wg.Wait()
	close(results)
	<-writerDone

	if err != nil {
		return "", 0, fmt.Errorf("traversal error: %v", err)
	}

	return outputFileName, totalTokens, nil
}

// generateTree acts as a robust recursive directory-mapping printer using an io.Writer interface.
func generateTree(rootDir, currentDir, prefix, outputFile string, w io.Writer, ie *IgnoreEngine) {
	entries, err := os.ReadDir(currentDir)
	if err != nil {
		return
	}

	var validEntries []fs.DirEntry
	for _, entry := range entries {
		info, err := entry.Info()
		if err != nil {
			continue
		}

		relPath, relErr := filepath.Rel(rootDir, filepath.Join(currentDir, entry.Name()))
		if relErr != nil {
			continue
		}

		lowerName := strings.ToLower(entry.Name())

		// Zero-Bug Safety: Check against IgnoreEngine, Symlinks, and self-generation files.
		if !ie.IsIgnored(relPath, entry.IsDir()) &&
			info.Mode()&os.ModeSymlink == 0 &&
			entry.Name() != outputFile &&
			lowerName != "p2m.exe" &&
			lowerName != "p2m" &&
			lowerName != "project2markdown.exe" &&
			lowerName != "project2markdown.go" &&
			!strings.Contains(lowerName, "_context.") {
			validEntries = append(validEntries, entry)
		}
	}

	for i, entry := range validEntries {
		isLast := i == len(validEntries)-1
		connector := "├── "
		if isLast {
			connector = "└── "
		}

		_, _ = fmt.Fprintf(w, "%s%s%s\n", prefix, connector, entry.Name())

		if entry.IsDir() {
			indent := "│   "
			if isLast {
				indent = "    "
			}
			generateTree(rootDir, filepath.Join(currentDir, entry.Name()), prefix+indent, outputFile, w, ie)
		}
	}
}

// streamFileContents opens the source file and safely streams its content line-by-line.
func streamFileContents(srcPath string, dstFile StringWriter, format string, removeComments, removeEmptyLines bool, ext string) (int, int, error) {
	srcFile, err := os.Open(srcPath)
	if err != nil {
		return 0, 0, err
	}
	defer srcFile.Close()

	scanner := bufio.NewScanner(srcFile)
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, MaxLineBuffer)

	charCount := 0
	tokenCount := 0

	for scanner.Scan() {
		line := scanner.Text()

		// Minification Filters
		if removeEmptyLines && strings.TrimSpace(line) == "" {
			continue
		}
		if removeComments && utils.IsSafeCommentLine(line, ext) {
			continue
		}
		charCount += len(line) + 1 // +1 for newline
		tokenCount += utils.EstimateTokens(line)

		// Performance Pillar: Avoid string concatenation (line + "\n") to prevent massive memory allocations
		switch format {
		case "md":
			if strings.Contains(line, "```") {
				line = strings.ReplaceAll(line, "```", "` ` `")
			}
			_, err = dstFile.WriteString(line)
			if err == nil {
				_, err = dstFile.WriteString("\n")
			}
		case "xml":
			if strings.Contains(line, "]]>") {
				line = strings.ReplaceAll(line, "]]>", "]] >")
			}
			_, err = dstFile.WriteString(line)
			if err == nil {
				_, err = dstFile.WriteString("\n")
			}
		case "json":
			escaped := utils.EscapeJSONString(line)
			_, err = dstFile.WriteString(escaped)
			if err == nil {
				_, err = dstFile.WriteString("\\n")
			}
		}

		if err != nil {
			return charCount, tokenCount, err
		}
	}

	if err := scanner.Err(); err != nil {
		if err == bufio.ErrTooLong && format == "md" {
			_, _ = dstFile.WriteString(fmt.Sprintf("\n// [Zero-Bug Warning: Single raw line exceeded safe threshold of %d MB]\n", MaxLineBuffer/(1024*1024)))
		}
		return charCount, tokenCount, err
	}

	return charCount, tokenCount, nil
}
